"brief.txt": {
        // ...
    },
    "candidates.log": {
        // ...
    },
    "credentials.txt": {
        // ...
    },
    // ...
const PROMPT = "recruit@dcib:~$";

// ...
this.printLine(PROMPT);